// Seed dei connettori fornitori servizi: fotografia di un profilo già in uso,
// con un connettore in errore e uno mai sincronizzato, così la vista mostra
// tutti gli stati possibili senza doverli provocare a mano.

import type { FornitoreServiziConnector } from './fornitori-types'

const isoOreFa = (ore: number): string =>
  new Date(Date.now() - ore * 60 * 60 * 1000).toISOString()

export const FORNITORI_SERVIZI_INIT: FornitoreServiziConnector[] = [
  {
    id: 'fs-getyourguide',
    nome: 'GetYourGuide — Italia',
    provider: 'getyourguide',
    descrizione: 'Tour ed esperienze nelle città italiane, con biglietti salta-fila.',
    baseUrl: 'https://api.getyourguide.com/1',
    authMode: 'api-key',
    credentials: { apiKey: 'gyg_live_8f3c9a21b4e7' },
    syncFrequency: 'hourly',
    ultimoSync: isoOreFa(2),
    statoSync: 'ok',
    messaggioSync: '1.284 servizi allineati, 12 nuovi, 3 rimossi',
    serviziImportati: 1284,
    filtri: {
      paesi: ['IT'],
      citta: ['Roma', 'Firenze', 'Venezia', 'Milano', 'Napoli'],
      categorie: ['Guided tours', 'Skip the line', 'Day trips'],
      prezzoMax: 400,
      soloConDisponibilita: true,
    },
    pubblicazione: 'auto',
    politicaRimozione: 'disattiva',
    categoryMapping: [
      { categoriaFornitore: 'Guided tours',    tipoServizio: 'attrazione' },
      { categoriaFornitore: 'Skip the line',   tipoServizio: 'museo' },
      { categoriaFornitore: 'Day trips',       tipoServizio: 'escursione' },
      { categoriaFornitore: 'Water activities', tipoServizio: '' },
    ],
    fieldMapping: [
      { partnerField: 'title',            sibyllaField: 'nome',        trasformazione: 'trim' },
      { partnerField: 'abstract',         sibyllaField: 'descrizione', trasformazione: '' },
      { partnerField: 'duration_minutes', sibyllaField: 'durata',      trasformazione: 'min→h' },
      { partnerField: 'city',             sibyllaField: 'citta',       trasformazione: '' },
    ],
    canali: {
      agora: { abilitato: true,  markup: 12, taglineOverride: 'Esperienze selezionate per la tua struttura' },
      b2b:   { abilitato: true,  markup: 18, taglineOverride: '' },
      b2c:   { abilitato: true,  markup: 25, taglineOverride: '' },
    },
    uiOverride: {
      logoUrl: '',
      paletteAccent: '#FF5533',
      mostraBadgeFornitore: true,
    },
    attivo: true,
  },
  {
    id: 'fs-tiqets',
    nome: 'Tiqets — Musei e attrazioni',
    provider: 'tiqets',
    descrizione: 'Biglietti a ingresso immediato per musei e monumenti.',
    baseUrl: 'https://api.tiqets.com/v2',
    authMode: 'bearer',
    credentials: { bearerToken: 'tq_prod_5b1e77c0d9' },
    syncFrequency: 'every-4h',
    ultimoSync: isoOreFa(9),
    statoSync: 'errore',
    messaggioSync: 'HTTP 401 — token scaduto: rigenera le credenziali del fornitore',
    serviziImportati: 342,
    filtri: {
      paesi: ['IT', 'ES'],
      citta: [],
      categorie: ['Museums', 'Landmarks'],
      prezzoMax: 0,
      soloConDisponibilita: true,
    },
    pubblicazione: 'auto',
    politicaRimozione: 'disattiva',
    categoryMapping: [
      { categoriaFornitore: 'Museums',   tipoServizio: 'museo' },
      { categoriaFornitore: 'Landmarks', tipoServizio: 'attrazione' },
    ],
    fieldMapping: [
      { partnerField: 'product_name', sibyllaField: 'nome',        trasformazione: 'trim' },
      { partnerField: 'summary',      sibyllaField: 'descrizione', trasformazione: '' },
    ],
    canali: {
      agora: { abilitato: true,  markup: 10, taglineOverride: '' },
      b2b:   { abilitato: false, markup: 15, taglineOverride: '' },
      b2c:   { abilitato: true,  markup: 20, taglineOverride: '' },
    },
    uiOverride: { logoUrl: '', paletteAccent: '#F45B69', mostraBadgeFornitore: true },
    attivo: true,
  },
  {
    id: 'fs-discovercars',
    nome: 'Discover Cars — Noleggio',
    provider: 'discovercars',
    descrizione: 'Noleggio veicoli con ritiro in aeroporto e in città.',
    baseUrl: 'https://api.discovercars.com/v2',
    authMode: 'basic',
    credentials: { username: 'sibylla_net', password: '••••••••' },
    syncFrequency: 'daily',
    ultimoSync: isoOreFa(20),
    statoSync: 'ok',
    messaggioSync: '96 servizi allineati',
    serviziImportati: 96,
    filtri: {
      paesi: ['IT'],
      citta: ['Roma', 'Milano', 'Catania'],
      categorie: ['Car rental', 'Airport pickup'],
      prezzoMax: 0,
      soloConDisponibilita: false,
    },
    pubblicazione: 'moderazione',
    politicaRimozione: 'mantieni',
    categoryMapping: [
      { categoriaFornitore: 'Car rental',     tipoServizio: 'noleggio-veicolo' },
      { categoriaFornitore: 'Airport pickup', tipoServizio: '' },
    ],
    fieldMapping: [
      { partnerField: 'vehicle_class', sibyllaField: 'nome',  trasformazione: '' },
      { partnerField: 'pickup_city',   sibyllaField: 'citta', trasformazione: '' },
    ],
    canali: {
      agora: { abilitato: true,  markup: 8,  taglineOverride: '' },
      b2b:   { abilitato: true,  markup: 12, taglineOverride: '' },
      b2c:   { abilitato: false, markup: 0,  taglineOverride: '' },
    },
    uiOverride: { logoUrl: '', paletteAccent: '#0F6FC5', mostraBadgeFornitore: false },
    attivo: true,
  },
  {
    id: 'fs-radical',
    nome: 'Radical Storage — Bagagli',
    provider: 'radical',
    descrizione: 'Deposito bagagli nelle città servite dalla rete.',
    baseUrl: 'https://api.radicalstorage.com/v1',
    authMode: 'bearer',
    credentials: {},
    syncFrequency: 'manual',
    statoSync: 'mai-eseguito',
    messaggioSync: 'In attesa di prima sincronizzazione',
    serviziImportati: 0,
    filtri: {
      paesi: ['IT'],
      citta: [],
      categorie: [],
      prezzoMax: 0,
      soloConDisponibilita: false,
    },
    pubblicazione: 'moderazione',
    politicaRimozione: 'disattiva',
    categoryMapping: [
      { categoriaFornitore: 'Luggage storage', tipoServizio: 'deposito-bagagli' },
      { categoriaFornitore: 'City services',   tipoServizio: '' },
    ],
    fieldMapping: [],
    canali: {
      agora: { abilitato: false, markup: 0, taglineOverride: '' },
      b2b:   { abilitato: false, markup: 0, taglineOverride: '' },
      b2c:   { abilitato: false, markup: 0, taglineOverride: '' },
    },
    uiOverride: { logoUrl: '', paletteAccent: '#00B2A9', mostraBadgeFornitore: true },
    attivo: false,
  },
]
