import type { Servizio } from './servizi-types'

// Seed inventato di servizi: 18 voci coprono tutti i tipi e diverse città
// italiane. Listini in tre fasce: Agorà, B2B, B2C.

export const SERVIZI_INIT: Servizio[] = [
  // ─── Escursioni ─────────────────────────────────────────────────────────
  {
    id: 'srv-esc-cinque-terre',
    tipo: 'escursione',
    nome: 'Tour Cinque Terre in barca',
    descrizione: 'Giornata in barca lungo la costa delle Cinque Terre con sosta bagno e pranzo a bordo',
    citta: 'La Spezia',
    paese: 'Italia',
    immagineUrl: 'https://images.unsplash.com/photo-1564499106-2d6f7af20a2c?w=600',
    disponibileDal: '2026-04-01',
    disponibileAl:  '2026-10-31',
    adultiMax:  12,
    bambiniMax: 6,
    pricingMode: 'per-persona',
    prezzoAgora: 99,
    prezzoB2B:   85,
    prezzoB2C:   119,
    durata: '8h',
    caratteristiche: ['Pranzo incluso', 'Sosta bagno', 'Skipper locale'],
    fornitoreNome: 'Liguria Boat Tours',
    sitoFornitore: 'liguriaboattours.it',
    attivo: true,
    pubblicato: true,
  },
  {
    id: 'srv-esc-dolomiti-trek',
    tipo: 'escursione',
    nome: 'Trekking guidato Dolomiti — Tre Cime',
    descrizione: 'Anello delle Tre Cime di Lavaredo con guida alpina UIAGM, durata 5 ore',
    citta: 'Cortina d\'Ampezzo',
    paese: 'Italia',
    immagineUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600',
    disponibileDal: '2026-06-15',
    disponibileAl:  '2026-09-30',
    adultiMax:  10,
    bambiniMax: 4,
    pricingMode: 'per-persona',
    prezzoAgora: 75,
    prezzoB2B:   65,
    prezzoB2C:   95,
    durata: '5h',
    caratteristiche: ['Guida alpina', 'Difficoltà media', 'Pranzo al sacco'],
    fornitoreNome: 'Dolomiti Adventure',
    sitoFornitore: 'dolomitiadventure.com',
    attivo: true,
    pubblicato: true,
  },

  // ─── Noleggio veicoli ───────────────────────────────────────────────────
  {
    id: 'srv-rent-fiat-500',
    tipo: 'noleggio-veicolo',
    nome: 'Noleggio Fiat 500 — citycar',
    descrizione: 'Noleggio giornaliero Fiat 500 1.0 hybrid, km illimitati, assicurazione kasko inclusa',
    citta: 'Roma',
    paese: 'Italia',
    immagineUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=600',
    disponibileDal: '2026-01-01',
    disponibileAl:  '2026-12-31',
    adultiMax:  4,
    bambiniMax: 0,
    pricingMode: 'per-giorno',
    prezzoAgora: 35,
    prezzoB2B:   29,
    prezzoB2C:   45,
    durata: 'al giorno',
    caratteristiche: ['Km illimitati', 'Kasko inclusa', 'Cambio manuale'],
    fornitoreNome: 'Italian Rent',
    sitoFornitore: 'italianrent.it',
    attivo: true,
    pubblicato: true,
  },
  {
    id: 'srv-rent-suv',
    tipo: 'noleggio-veicolo',
    nome: 'SUV 7 posti — noleggio settimanale',
    descrizione: 'Noleggio settimanale SUV 7 posti automatico, ideale per famiglie o piccoli gruppi',
    citta: 'Milano',
    paese: 'Italia',
    immagineUrl: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=600',
    disponibileDal: '2026-01-01',
    disponibileAl:  '2026-12-31',
    adultiMax:  7,
    bambiniMax: 0,
    pricingMode: 'per-giorno',
    prezzoAgora: 89,
    prezzoB2B:   75,
    prezzoB2C:   119,
    durata: 'al giorno',
    caratteristiche: ['Automatico', 'GPS incluso', '2 seggiolini gratuiti'],
    fornitoreNome: 'EuroDrive',
    sitoFornitore: 'eurodrive.eu',
    attivo: true,
    pubblicato: true,
  },

  // ─── Deposito bagagli ───────────────────────────────────────────────────
  {
    id: 'srv-bag-roma-termini',
    tipo: 'deposito-bagagli',
    nome: 'Deposito bagagli — Roma Termini',
    descrizione: 'Custodia bagagli sicura presso la stazione Termini, aperto 7/7 dalle 6 alle 23',
    citta: 'Roma',
    paese: 'Italia',
    immagineUrl: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=600',
    disponibileDal: '2026-01-01',
    disponibileAl:  '2026-12-31',
    adultiMax:  0,
    bambiniMax: 0,
    pricingMode: 'per-ora',
    prezzoAgora: 4,
    prezzoB2B:   3,
    prezzoB2C:   6,
    durata: 'all\'ora a pezzo',
    caratteristiche: ['Aperto 7/7', 'Assicurazione fino a 1500€', 'Vicino stazione'],
    fornitoreNome: 'Stasher Italia',
    sitoFornitore: 'stasher.it',
    attivo: true,
    pubblicato: true,
  },
  {
    id: 'srv-bag-milano-duomo',
    tipo: 'deposito-bagagli',
    nome: 'Deposito bagagli — Milano Duomo',
    descrizione: 'Custodia bagagli a 200m dal Duomo, prenotabile online con check-in QR',
    citta: 'Milano',
    paese: 'Italia',
    immagineUrl: 'https://images.unsplash.com/photo-1551867633-194f125bddfa?w=600',
    disponibileDal: '2026-01-01',
    disponibileAl:  '2026-12-31',
    adultiMax:  0,
    bambiniMax: 0,
    pricingMode: 'per-ora',
    prezzoAgora: 5,
    prezzoB2B:   4,
    prezzoB2C:   7,
    durata: 'all\'ora a pezzo',
    caratteristiche: ['Check-in QR code', 'Videosorveglianza', 'Aperto 9-21'],
    fornitoreNome: 'LuggageHero',
    sitoFornitore: 'luggagehero.com',
    attivo: true,
    pubblicato: true,
  },

  // ─── Parchi divertimenti ────────────────────────────────────────────────
  {
    id: 'srv-park-gardaland',
    tipo: 'parco-divertimenti',
    nome: 'Gardaland — biglietto giornaliero',
    descrizione: 'Ingresso giornaliero al parco di Gardaland, accesso a tutte le attrazioni',
    citta: 'Castelnuovo del Garda',
    paese: 'Italia',
    immagineUrl: 'https://images.unsplash.com/photo-1582467049-12fdc4e3aae9?w=600',
    disponibileDal: '2026-04-05',
    disponibileAl:  '2026-11-04',
    adultiMax:  20,
    bambiniMax: 20,
    pricingMode: 'per-persona',
    prezzoAgora: 42,
    prezzoB2B:   36,
    prezzoB2C:   52,
    durata: '1 giorno',
    caratteristiche: ['Tutte le attrazioni', 'Bambini sotto 1m gratis'],
    fornitoreNome: 'Gardaland S.r.l.',
    sitoFornitore: 'gardaland.it',
    attivo: true,
    pubblicato: true,
  },
  {
    id: 'srv-park-mirabilandia',
    tipo: 'parco-divertimenti',
    nome: 'Mirabilandia + Mirabeach — combo',
    descrizione: 'Biglietto combinato parco + acquapark, valido per la stessa giornata',
    citta: 'Savio (Ravenna)',
    paese: 'Italia',
    immagineUrl: 'https://images.unsplash.com/photo-1601751818941-571144562ff8?w=600',
    disponibileDal: '2026-06-01',
    disponibileAl:  '2026-09-15',
    adultiMax:  20,
    bambiniMax: 20,
    pricingMode: 'per-persona',
    prezzoAgora: 48,
    prezzoB2B:   42,
    prezzoB2C:   59,
    durata: '1 giorno',
    caratteristiche: ['Combo parco+acqua', 'Salta-fila incluso'],
    fornitoreNome: 'Mirabilandia',
    sitoFornitore: 'mirabilandia.it',
    attivo: true,
    pubblicato: true,
  },

  // ─── Musei ──────────────────────────────────────────────────────────────
  {
    id: 'srv-mus-uffizi',
    tipo: 'museo',
    nome: 'Galleria degli Uffizi — biglietto salta-fila',
    descrizione: 'Ingresso prioritario con orario riservato alla Galleria degli Uffizi',
    citta: 'Firenze',
    paese: 'Italia',
    immagineUrl: 'https://images.unsplash.com/photo-1554907984-15263bfd63bd?w=600',
    disponibileDal: '2026-01-01',
    disponibileAl:  '2026-12-31',
    adultiMax:  30,
    bambiniMax: 30,
    pricingMode: 'per-persona',
    prezzoAgora: 25,
    prezzoB2B:   22,
    prezzoB2C:   32,
    durata: '2h',
    caratteristiche: ['Salta-fila', 'Audioguida disponibile', 'Riduzione under 18'],
    fornitoreNome: 'Gallerie degli Uffizi',
    sitoFornitore: 'uffizi.it',
    attivo: true,
    pubblicato: true,
  },
  {
    id: 'srv-mus-vaticano',
    tipo: 'museo',
    nome: 'Musei Vaticani + Cappella Sistina',
    descrizione: 'Ingresso ai Musei Vaticani con accesso alla Cappella Sistina, salta-fila incluso',
    citta: 'Roma',
    paese: 'Italia',
    immagineUrl: 'https://images.unsplash.com/photo-1542820229-081e0c12af0b?w=600',
    disponibileDal: '2026-01-01',
    disponibileAl:  '2026-12-31',
    adultiMax:  30,
    bambiniMax: 30,
    pricingMode: 'per-persona',
    prezzoAgora: 32,
    prezzoB2B:   28,
    prezzoB2C:   42,
    durata: '3h',
    caratteristiche: ['Salta-fila', 'Cappella Sistina inclusa', 'Audioguida disponibile'],
    fornitoreNome: 'Musei Vaticani',
    sitoFornitore: 'museivaticani.va',
    attivo: true,
    pubblicato: true,
  },

  // ─── Attrazioni / Tour ──────────────────────────────────────────────────
  {
    id: 'srv-attr-colosseo',
    tipo: 'attrazione',
    nome: 'Colosseo — Tour Arena & Foro Romano',
    descrizione: 'Tour guidato del Colosseo con accesso speciale all\'arena e visita al Foro Romano',
    citta: 'Roma',
    paese: 'Italia',
    immagineUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=600',
    disponibileDal: '2026-01-01',
    disponibileAl:  '2026-12-31',
    adultiMax:  25,
    bambiniMax: 15,
    pricingMode: 'per-persona',
    prezzoAgora: 55,
    prezzoB2B:   48,
    prezzoB2C:   72,
    durata: '3h',
    caratteristiche: ['Accesso arena', 'Guida ufficiale', 'Foro Romano incluso'],
    fornitoreNome: 'Walks of Italy',
    sitoFornitore: 'walksofitaly.com',
    attivo: true,
    pubblicato: true,
  },
  {
    id: 'srv-attr-gondola',
    tipo: 'attrazione',
    nome: 'Giro in gondola — Canal Grande',
    descrizione: 'Esperienza romantica di 30 minuti in gondola lungo il Canal Grande di Venezia',
    citta: 'Venezia',
    paese: 'Italia',
    immagineUrl: 'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=600',
    disponibileDal: '2026-01-01',
    disponibileAl:  '2026-12-31',
    adultiMax:  6,
    bambiniMax: 2,
    pricingMode: 'per-gruppo',
    prezzoAgora: 90,
    prezzoB2B:   75,
    prezzoB2C:   120,
    durata: '30min',
    caratteristiche: ['Gondoliere veneziano', 'Fino a 6 persone'],
    fornitoreNome: 'Gondolieri Venezia',
    attivo: true,
    pubblicato: true,
  },

  // ─── Eventi ─────────────────────────────────────────────────────────────
  {
    id: 'srv-evt-fashion-week',
    tipo: 'evento',
    nome: 'Milano Fashion Week — accesso sfilata',
    descrizione: 'Pass per una sfilata della Milano Fashion Week con accesso area stampa/buyer',
    citta: 'Milano',
    paese: 'Italia',
    immagineUrl: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=600',
    disponibileDal: '2026-09-20',
    disponibileAl:  '2026-09-26',
    adultiMax:  4,
    bambiniMax: 0,
    pricingMode: 'per-persona',
    prezzoAgora: 280,
    prezzoB2B:   240,
    prezzoB2C:   380,
    durata: '2h',
    caratteristiche: ['Accesso buyer/press', 'Welcome cocktail', 'Posto numerato'],
    fornitoreNome: 'Camera della Moda',
    sitoFornitore: 'cameramoda.it',
    attivo: true,
    pubblicato: true,
  },
  {
    id: 'srv-evt-vinitaly',
    tipo: 'evento',
    nome: 'Vinitaly — biglietto giornaliero',
    descrizione: 'Ingresso al Salone Internazionale dei Vini e Distillati di Verona',
    citta: 'Verona',
    paese: 'Italia',
    immagineUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600',
    disponibileDal: '2026-04-12',
    disponibileAl:  '2026-04-15',
    adultiMax:  10,
    bambiniMax: 0,
    pricingMode: 'per-persona',
    prezzoAgora: 75,
    prezzoB2B:   60,
    prezzoB2C:   95,
    durata: '1 giorno',
    caratteristiche: ['Solo operatori', 'Degustazioni illimitate', 'Catalogo digitale'],
    fornitoreNome: 'Veronafiere',
    sitoFornitore: 'vinitaly.com',
    attivo: true,
    pubblicato: true,
  },

  // ─── Concerti ───────────────────────────────────────────────────────────
  {
    id: 'srv-conc-stadio-sansiro',
    tipo: 'concerto',
    nome: 'Concerto live — Stadio San Siro',
    descrizione: 'Biglietti per concerto live presso lo Stadio Giuseppe Meazza, varie tipologie posto',
    citta: 'Milano',
    paese: 'Italia',
    immagineUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600',
    disponibileDal: '2026-06-10',
    disponibileAl:  '2026-09-30',
    adultiMax:  40,
    bambiniMax: 10,
    pricingMode: 'per-persona',
    prezzoAgora: 75,
    prezzoB2B:   60,
    prezzoB2C:   95,
    durata: '3h',
    caratteristiche: ['Vari settori', 'Servizio bar', 'Trasporti pubblici dedicati'],
    fornitoreNome: 'Live Nation Italia',
    sitoFornitore: 'livenation.it',
    attivo: true,
    pubblicato: true,
  },
  {
    id: 'srv-conc-arena-verona',
    tipo: 'concerto',
    nome: 'Arena di Verona — opera lirica',
    descrizione: 'Spettacolo di opera lirica all\'Arena di Verona, festival estivo',
    citta: 'Verona',
    paese: 'Italia',
    immagineUrl: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=600',
    disponibileDal: '2026-06-20',
    disponibileAl:  '2026-09-05',
    adultiMax:  30,
    bambiniMax: 6,
    pricingMode: 'per-persona',
    prezzoAgora: 120,
    prezzoB2B:   95,
    prezzoB2C:   165,
    durata: '3h',
    caratteristiche: ['Festival lirico storico', 'Programma di sala incluso'],
    fornitoreNome: 'Fondazione Arena di Verona',
    sitoFornitore: 'arena.it',
    attivo: true,
    pubblicato: true,
  },

  // ─── Eventi sportivi ────────────────────────────────────────────────────
  {
    id: 'srv-sport-juve-stadium',
    tipo: 'evento-sportivo',
    nome: 'Juventus — partita di Serie A',
    descrizione: 'Biglietto per partita di Serie A all\'Allianz Stadium, vari settori disponibili',
    citta: 'Torino',
    paese: 'Italia',
    immagineUrl: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?w=600',
    disponibileDal: '2026-08-15',
    disponibileAl:  '2027-05-31',
    adultiMax:  30,
    bambiniMax: 10,
    pricingMode: 'per-persona',
    prezzoAgora: 65,
    prezzoB2B:   55,
    prezzoB2C:   85,
    durata: '2h',
    caratteristiche: ['Allianz Stadium', 'Posti adiacenti', 'Pacchetto hospitality opzionale'],
    fornitoreNome: 'Juventus F.C.',
    sitoFornitore: 'juventus.com',
    attivo: true,
    pubblicato: true,
  },
  {
    id: 'srv-sport-gp-monza',
    tipo: 'evento-sportivo',
    nome: 'Gran Premio F1 — Monza',
    descrizione: 'Pacchetto 3 giorni Autodromo di Monza, accesso al Gran Premio d\'Italia',
    citta: 'Monza',
    paese: 'Italia',
    immagineUrl: 'https://images.unsplash.com/photo-1504707748692-419802cf939d?w=600',
    disponibileDal: '2026-09-04',
    disponibileAl:  '2026-09-06',
    adultiMax:  10,
    bambiniMax: 4,
    pricingMode: 'per-persona',
    prezzoAgora: 320,
    prezzoB2B:   270,
    prezzoB2C:   420,
    durata: '3 giorni',
    caratteristiche: ['3 giorni di paddock', 'Tribuna numerata', 'Gadget ufficiale'],
    fornitoreNome: 'Autodromo Nazionale Monza',
    sitoFornitore: 'monzanet.it',
    attivo: true,
    pubblicato: true,
  },
]
