import type { PartnerConnector } from './partner-types'

// Seed inventato di connettori partner che alimentano i canali di vendita
// Sibylla Network con inventario esterno.

export const PARTNER_CONNECTORS_INIT: PartnerConnector[] = [
  {
    id: 'pc-booking',
    nome: 'Booking.com — Italian inventory',
    provider: 'booking',
    descrizione: 'Feed Booking.com filtrato sulle strutture italiane affiliate al programma Sibylla.',
    baseUrl: 'https://distribution-xml.booking.com/2.x',
    authMode: 'basic',
    credentials: {
      username: 'sibylla_partner',
      password: '••••••••••••••••',
    },
    syncFrequency: 'hourly',
    ultimoSync: '2026-05-26T08:42:00Z',
    statoSync: 'ok',
    messaggioSync: '247 strutture aggiornate, 0 errori',
    struttureImportate: 247,
    filtri: {
      paesi: ['IT'],
      regioni: ['Lazio', 'Toscana', 'Veneto', 'Lombardia'],
      tipi: ['hotel', 'b&b'],
      classificazioneMin: '3★',
    },
    canali: {
      agora: { abilitato: true,  markup: 0,  taglineOverride: '' },
      b2b:   { abilitato: true,  markup: 8,  taglineOverride: 'Network rate confidenziale' },
      b2c:   { abilitato: false, markup: 15, taglineOverride: '' },
    },
    fieldMapping: [
      { partnerField: 'hotel_id',     sibyllaField: 'id',       trasformazione: 'prefix:bk-' },
      { partnerField: 'hotel_name',   sibyllaField: 'nome',     trasformazione: '' },
      { partnerField: 'address',      sibyllaField: 'indirizzo', trasformazione: '' },
      { partnerField: 'star_rating',  sibyllaField: 'classificazione', trasformazione: 'star→★' },
      { partnerField: 'city',         sibyllaField: 'citta',    trasformazione: '' },
    ],
    uiOverride: {
      logoUrl: '',
      paletteAccent: '#003580',
      mostraBadgePartner: true,
    },
    attivo: true,
  },
  {
    id: 'pc-hotelbeds',
    nome: 'Hotelbeds — Wholesaler EMEA',
    provider: 'hotelbeds',
    descrizione: 'Net rates Hotelbeds per il canale B2B Sibylla Network, mercato EMEA.',
    baseUrl: 'https://api.test.hotelbeds.com/hotel-api/1.0',
    authMode: 'api-key',
    credentials: {
      apiKey: '••••••••••••••••',
    },
    syncFrequency: 'every-4h',
    ultimoSync: '2026-05-26T05:00:00Z',
    statoSync: 'ok',
    messaggioSync: '1820 strutture sincronizzate',
    struttureImportate: 1820,
    filtri: {
      paesi: ['IT', 'ES', 'FR', 'GR'],
      regioni: [],
      tipi: ['hotel', 'resort'],
      classificazioneMin: '3★',
    },
    canali: {
      agora: { abilitato: false, markup: 0,  taglineOverride: '' },
      b2b:   { abilitato: true,  markup: 12, taglineOverride: 'Tariffa wholesale netta' },
      b2c:   { abilitato: false, markup: 25, taglineOverride: '' },
    },
    fieldMapping: [
      { partnerField: 'code',         sibyllaField: 'id',       trasformazione: 'prefix:hb-' },
      { partnerField: 'name.content', sibyllaField: 'nome',     trasformazione: 'trim' },
      { partnerField: 'category',     sibyllaField: 'classificazione', trasformazione: '' },
    ],
    uiOverride: {
      logoUrl: '',
      paletteAccent: '#00B5AD',
      mostraBadgePartner: false,
    },
    attivo: true,
  },
  {
    id: 'pc-ratehawk',
    nome: 'RateHawk — Bedbank globale',
    provider: 'ratehawk',
    descrizione: 'Bedbank RateHawk per inventario worldwide B2C e B2B.',
    baseUrl: 'https://api.ratehawk.com/v3',
    authMode: 'bearer',
    credentials: {
      bearerToken: '••••••••••••••••',
    },
    syncFrequency: 'daily',
    ultimoSync: '2026-05-25T22:00:00Z',
    statoSync: 'errore',
    messaggioSync: 'Timeout autenticazione (401) — verifica token',
    struttureImportate: 580,
    filtri: {
      paesi: ['IT', 'ES', 'PT', 'GR', 'HR'],
      regioni: [],
      tipi: ['hotel', 'apartment'],
      classificazioneMin: '4★',
    },
    canali: {
      agora: { abilitato: false, markup: 0,  taglineOverride: '' },
      b2b:   { abilitato: true,  markup: 10, taglineOverride: '' },
      b2c:   { abilitato: true,  markup: 22, taglineOverride: 'Bedbank globale — prezzi competitivi' },
    },
    fieldMapping: [
      { partnerField: 'id',           sibyllaField: 'id',       trasformazione: 'prefix:rh-' },
      { partnerField: 'name',         sibyllaField: 'nome',     trasformazione: '' },
      { partnerField: 'star_rating',  sibyllaField: 'classificazione', trasformazione: 'star→★' },
    ],
    uiOverride: {
      logoUrl: '',
      paletteAccent: '#FF8C00',
      mostraBadgePartner: true,
    },
    attivo: true,
  },
  {
    id: 'pc-airbnb',
    nome: 'Airbnb — Premium hosts Italia',
    provider: 'airbnb',
    descrizione: 'Selezione di host premium Airbnb su canale B2C Sibylla.',
    baseUrl: 'https://api.airbnb.com/v2',
    authMode: 'oauth2',
    credentials: {
      clientId: 'sibylla_app_id',
      clientSecret: '••••••••••••••••',
    },
    syncFrequency: 'hourly',
    ultimoSync: '2026-05-26T09:15:00Z',
    statoSync: 'in-corso',
    messaggioSync: 'Sincronizzazione in corso — pagina 7 di 12',
    struttureImportate: 134,
    filtri: {
      paesi: ['IT'],
      regioni: ['Sicilia', 'Sardegna', 'Puglia'],
      tipi: ['apartment', 'villa'],
      classificazioneMin: '4★',
    },
    canali: {
      agora: { abilitato: false, markup: 0,  taglineOverride: '' },
      b2b:   { abilitato: false, markup: 0,  taglineOverride: '' },
      b2c:   { abilitato: true,  markup: 18, taglineOverride: 'Case e ville selezionate da host premium' },
    },
    fieldMapping: [
      { partnerField: 'listing_id',   sibyllaField: 'id',       trasformazione: 'prefix:abnb-' },
      { partnerField: 'name',         sibyllaField: 'nome',     trasformazione: '' },
      { partnerField: 'city',         sibyllaField: 'citta',    trasformazione: '' },
    ],
    uiOverride: {
      logoUrl: '',
      paletteAccent: '#FF5A5F',
      mostraBadgePartner: true,
    },
    attivo: true,
  },
  {
    id: 'pc-siteminder-skyline',
    nome: 'SiteMinder — Skyline Hospitality',
    provider: 'siteminder',
    descrizione: 'Channel manager del gruppo Skyline Hospitality (3 strutture multi-property).',
    baseUrl: 'https://api.siteminder.com',
    authMode: 'oauth2',
    credentials: {
      clientId: 'skyline_oauth_client',
      clientSecret: '••••••••••••••••',
      tenantId: 'skyline-hosp-IT',
    },
    syncFrequency: '15min',
    ultimoSync: '2026-05-26T09:30:00Z',
    statoSync: 'ok',
    messaggioSync: '3 strutture, prezzi e availability aggiornati',
    struttureImportate: 3,
    filtri: {
      paesi: ['IT'],
      regioni: [],
      tipi: ['hotel'],
      classificazioneMin: '4★',
    },
    canali: {
      agora: { abilitato: true,  markup: 0,  taglineOverride: '' },
      b2b:   { abilitato: true,  markup: 5,  taglineOverride: '' },
      b2c:   { abilitato: true,  markup: 12, taglineOverride: '' },
    },
    fieldMapping: [
      { partnerField: 'property_id',  sibyllaField: 'id',       trasformazione: 'prefix:sm-' },
      { partnerField: 'property_name', sibyllaField: 'nome',     trasformazione: '' },
    ],
    uiOverride: {
      logoUrl: '',
      paletteAccent: '#27408B',
      mostraBadgePartner: false,
    },
    attivo: true,
  },
  {
    id: 'pc-custom-puglia',
    nome: 'Custom REST — Masserie Puglia',
    provider: 'custom',
    descrizione: 'Consorzio Masserie Puglia — endpoint REST custom con 28 strutture.',
    baseUrl: 'https://api.masseriepuglia.example/v2',
    authMode: 'api-key',
    credentials: {
      apiKey: '••••••••',
    },
    syncFrequency: 'manual',
    ultimoSync: undefined,
    statoSync: 'mai-eseguito',
    messaggioSync: 'In attesa di prima sincronizzazione',
    struttureImportate: 0,
    filtri: {
      paesi: ['IT'],
      regioni: ['Puglia'],
      tipi: ['agriturismo', 'villa'],
      classificazioneMin: '3★',
    },
    canali: {
      agora: { abilitato: false, markup: 0,  taglineOverride: '' },
      b2b:   { abilitato: false, markup: 0,  taglineOverride: '' },
      b2c:   { abilitato: false, markup: 0,  taglineOverride: '' },
    },
    fieldMapping: [],
    uiOverride: {
      logoUrl: '',
      paletteAccent: '#5C5C5C',
      mostraBadgePartner: true,
    },
    attivo: false,
  },
]
