"""
Patch script: adds Wallet/Cliente endpoints to main.py.
Run from backend directory:
  venv\Scripts\python.exe apply_wallet_patch.py
Safe to run multiple times (idempotent).
"""
import os, sys, ast, secrets

MAIN_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'app', 'main.py')
if not os.path.exists(MAIN_PATH):
    print("ERROR: app/main.py not found"); sys.exit(1)

main = open(MAIN_PATH, encoding='utf-8').read()

if '/api/clienti' in main:
    print("Already patched."); sys.exit(0)

# Add imports
if 'Cliente' not in main:
    main = main.replace(
        'WebMenu, WebMenuVoce,',
        'WebMenu, WebMenuVoce,\n    Cliente, Wallet, WalletTransazione,'
    )
    if 'Cliente' not in main:
        # WebMenu not yet patched — add to existing import
        for marker in ['Monitor, VoceMenuMonitor,', 'VoceMenuStampante,']:
            if marker in main:
                main = main.replace(marker, marker + '\n    Cliente, Wallet, WalletTransazione,')
                break
    print("  + Cliente/Wallet/WalletTransazione imported")

WALLET_CODE = (
'\n'
'# -- Clienti ----------------------------------------------------------------\n'
'\n'
'@app.get("/api/clienti")\n'
'def get_clienti():\n'
'    db = get_db()\n'
'    try:\n'
'        q = db.query(Cliente)\n'
'        if request.args.get("q"):\n'
'            s = "%" + request.args["q"] + "%"\n'
'            q = q.filter((Cliente.nome.ilike(s))|(Cliente.cognome.ilike(s))|(Cliente.email.ilike(s)))\n'
'        return ok([c.to_dict() for c in q.order_by(Cliente.cognome, Cliente.nome).all()])\n'
'    finally: db.close()\n'
'\n'
'\n'
'@app.post("/api/clienti")\n'
'def create_cliente():\n'
'    db = get_db()\n'
'    try:\n'
'        d = body()\n'
'        if not d.get("nome"): return err("Nome obbligatorio")\n'
'        c = Cliente(nome=d["nome"], cognome=d.get("cognome",""),\n'
'                    email=d.get("email",""), telefono=d.get("telefono",""),\n'
'                    note=d.get("note",""),\n'
'                    categoria_cliente_id=int(d["categoria_cliente_id"]) if d.get("categoria_cliente_id") else None)\n'
'        db.add(c); db.commit(); db.refresh(c)\n'
'        return ok(c.to_dict())\n'
'    except Exception as e: db.rollback(); return err(str(e))\n'
'    finally: db.close()\n'
'\n'
'\n'
'@app.put("/api/clienti/<int:cid>")\n'
'def update_cliente(cid):\n'
'    db = get_db()\n'
'    try:\n'
'        c = db.get(Cliente, cid)\n'
'        if not c: return err("Non trovato", 404)\n'
'        d = body()\n'
'        for k in ("nome","cognome","email","telefono","note"):\n'
'            if k in d: setattr(c, k, d[k])\n'
'        if "categoria_cliente_id" in d:\n'
'            c.categoria_cliente_id = int(d["categoria_cliente_id"]) if d["categoria_cliente_id"] else None\n'
'        db.commit(); db.refresh(c)\n'
'        return ok(c.to_dict())\n'
'    except Exception as e: db.rollback(); return err(str(e))\n'
'    finally: db.close()\n'
'\n'
'\n'
'@app.delete("/api/clienti/<int:cid>")\n'
'def delete_cliente(cid):\n'
'    db = get_db()\n'
'    try:\n'
'        c = db.get(Cliente, cid)\n'
'        if not c: return err("Non trovato", 404)\n'
'        db.delete(c); db.commit()\n'
'        return ok({"deleted": cid})\n'
'    except Exception as e: db.rollback(); return err(str(e))\n'
'    finally: db.close()\n'
'\n'
'\n'
'# -- Wallets -----------------------------------------------------------------\n'
'\n'
'@app.get("/api/wallets")\n'
'def get_wallets():\n'
'    db = get_db()\n'
'    try:\n'
'        q = db.query(Wallet)\n'
'        if request.args.get("cliente_id"): q = q.filter(Wallet.cliente_id==int(request.args["cliente_id"]))\n'
'        if request.args.get("outlet_id"):  q = q.filter(Wallet.outlet_id==int(request.args["outlet_id"]))\n'
'        return ok([w.to_dict() for w in q.order_by(Wallet.created_at.desc()).all()])\n'
'    finally: db.close()\n'
'\n'
'\n'
'@app.get("/api/wallets/scan/<token>")\n'
'def scan_wallet(token):\n'
'    """Public endpoint: identify wallet by QR token."""\n'
'    db = get_db()\n'
'    try:\n'
'        w = db.query(Wallet).filter(Wallet.token==token).first()\n'
'        if not w: return err("Wallet non trovato", 404)\n'
'        if not w.attivo: return err("Wallet disattivato", 403)\n'
'        from datetime import datetime as _dt\n'
'        if w.data_scadenza and str(w.data_scadenza) < _dt.utcnow().strftime("%Y-%m-%d"):\n'
'            return err("Wallet scaduto", 403)\n'
'        data = w.to_dict()\n'
'        data["transazioni_recenti"] = [t.to_dict() for t in\n'
'            db.query(WalletTransazione).filter(WalletTransazione.wallet_id==w.id)\n'
'            .order_by(WalletTransazione.created_at.desc()).limit(10).all()]\n'
'        return ok(data)\n'
'    finally: db.close()\n'
'\n'
'\n'
'@app.post("/api/wallets")\n'
'def create_wallet():\n'
'    db = get_db()\n'
'    try:\n'
'        d = body()\n'
'        if not d.get("cliente_id"): return err("cliente_id obbligatorio")\n'
'        import secrets as _sec\n'
'        token = _sec.token_urlsafe(32)\n'
'        w = Wallet(cliente_id=int(d["cliente_id"]),\n'
'                   outlet_id=int(d["outlet_id"]) if d.get("outlet_id") else None,\n'
'                   etichetta=d.get("etichetta","Wallet"),\n'
'                   saldo=float(d.get("saldo_iniziale",0)),\n'
'                   token=token, attivo=True,\n'
'                   data_scadenza=d.get("data_scadenza"))\n'
'        db.add(w)\n'
'        if float(d.get("saldo_iniziale",0)) > 0:\n'
'            db.flush()\n'
'            db.add(WalletTransazione(wallet_id=w.id, tipo="ricarica",\n'
'                importo=float(d["saldo_iniziale"]), note="Ricarica iniziale"))\n'
'        db.commit(); db.refresh(w)\n'
'        return ok(w.to_dict())\n'
'    except Exception as e: db.rollback(); return err(str(e))\n'
'    finally: db.close()\n'
'\n'
'\n'
'@app.put("/api/wallets/<int:wid>")\n'
'def update_wallet(wid):\n'
'    db = get_db()\n'
'    try:\n'
'        w = db.get(Wallet, wid)\n'
'        if not w: return err("Non trovato", 404)\n'
'        d = body()\n'
'        for k in ("etichetta","attivo","data_scadenza"):\n'
'            if k in d: setattr(w, k, d[k])\n'
'        db.commit(); db.refresh(w)\n'
'        return ok(w.to_dict())\n'
'    except Exception as e: db.rollback(); return err(str(e))\n'
'    finally: db.close()\n'
'\n'
'\n'
'@app.delete("/api/wallets/<int:wid>")\n'
'def delete_wallet(wid):\n'
'    db = get_db()\n'
'    try:\n'
'        w = db.get(Wallet, wid)\n'
'        if not w: return err("Non trovato", 404)\n'
'        db.delete(w); db.commit()\n'
'        return ok({"deleted": wid})\n'
'    except Exception as e: db.rollback(); return err(str(e))\n'
'    finally: db.close()\n'
'\n'
'\n'
'@app.post("/api/wallets/<int:wid>/ricarica")\n'
'def ricarica_wallet(wid):\n'
'    db = get_db()\n'
'    try:\n'
'        w = db.get(Wallet, wid)\n'
'        if not w: return err("Non trovato", 404)\n'
'        d = body()\n'
'        importo = float(d.get("importo",0))\n'
'        if importo <= 0: return err("Importo deve essere positivo")\n'
'        w.saldo = (w.saldo or 0) + importo\n'
'        t = WalletTransazione(wallet_id=wid, tipo="ricarica", importo=importo,\n'
'                               note=d.get("note","Ricarica"))\n'
'        db.add(t); db.commit(); db.refresh(w)\n'
'        return ok(w.to_dict())\n'
'    except Exception as e: db.rollback(); return err(str(e))\n'
'    finally: db.close()\n'
'\n'
'\n'
'@app.post("/api/wallets/<int:wid>/paga")\n'
'def paga_wallet(wid):\n'
'    """Scalare dal wallet. Checks: active, not expired, sufficient balance."""\n'
'    db = get_db()\n'
'    try:\n'
'        w = db.get(Wallet, wid)\n'
'        if not w: return err("Wallet non trovato", 404)\n'
'        if not w.attivo: return err("Wallet disattivato", 403)\n'
'        from datetime import datetime as _dt\n'
'        if w.data_scadenza and str(w.data_scadenza) < _dt.utcnow().strftime("%Y-%m-%d"):\n'
'            return err("Wallet scaduto", 403)\n'
'        d = body()\n'
'        importo = float(d.get("importo",0))\n'
'        if importo <= 0: return err("Importo deve essere positivo")\n'
'        if (w.saldo or 0) < importo: return err(f"Credito insufficiente (disponibile: €{w.saldo:.2f})", 402)\n'
'        w.saldo = (w.saldo or 0) - importo\n'
'        t = WalletTransazione(wallet_id=wid, tipo="pagamento", importo=-importo,\n'
'                               note=d.get("note","Pagamento comanda"),\n'
'                               comanda_id=int(d["comanda_id"]) if d.get("comanda_id") else None)\n'
'        db.add(t); db.commit(); db.refresh(w)\n'
'        return ok(w.to_dict())\n'
'    except Exception as e: db.rollback(); return err(str(e))\n'
'    finally: db.close()\n'
'\n'
'\n'
'@app.get("/api/wallets/<int:wid>/movimenti")\n'
'def get_movimenti(wid):\n'
'    db = get_db()\n'
'    try:\n'
'        rows = db.query(WalletTransazione).filter(WalletTransazione.wallet_id==wid)\\\n'
'                  .order_by(WalletTransazione.created_at.desc()).all()\n'
'        return ok([r.to_dict() for r in rows])\n'
'    finally: db.close()\n'
'\n'
'\n'
)

insert_before = '# -- Web Menu'
if insert_before not in main:
    insert_before = '# -- Monitor KDS'
if insert_before not in main:
    insert_before = '@app.get("/api/utenti")'

main = main.replace(insert_before, WALLET_CODE + insert_before, 1)
print("  + Wallet/Cliente endpoints added")

try:
    ast.parse(main)
except SyntaxError as e:
    print(f"SYNTAX ERROR line {e.lineno}: {e.msg}"); sys.exit(1)

open(MAIN_PATH, 'w', encoding='utf-8').write(main)
print(f"Done! main.py: {len(main.splitlines())} lines")
print("Next: venv\\Scripts\\python.exe migrate_wallet.py && restart.bat")
