// ─── Sottotitoli pagina ────────────────────────────────────────────────────────
// Generato dalla colonna "SOTTOTITOLI" di menu_sottotitoli.xlsx (fogli SideBar TO + Full).
// Mappa pageId → sottotitolo, usata da GenericPage (e disponibile alle pagine dedicate).
export const PAGE_SUBTITLES: Record<string, string> = {
  "acquisti-servizi": "Gestisci i servizi e attiva le soluzioni più adatte alle tue esigenze operative",
  "action-centre": "Suggerimenti data-driven per la gestione di offerte e disponiblità verso il mercato",
  "adr-analysis": "Monitoraggio in tempo reale del ricavo medio camera per singolo operatore e tipologia di camera",
  "allocazione-risorse": "Ripartizione delle prenotazioni nelle camere al fine di ottimizzarne la capienza",
  "anagrafiche-op": "Gestisci i profili degli ospiti in modo centralizzato",
  "analisi-booking": "Dashboard su revenue, tasso di occupazione, giorni extra e servizi venduti",
  "analisi-dist-sales": "Esplorazione analitica della distribuzione basata su dati granulari e KPI strategici per guidare decisioni mirate",
  "analisi-occ": "Monitoraggio dei livelli di occupazione e dei trend di prenotazione",
  "analisi-scenari-mensili": "Monitoraggio e confronto delle performance su base mensile",
  "archivio-contratti": "Panoramica completa dei contratti registrati",
  "archivio-personale": "Visualizza e gestisci tutte le anagrafiche dei dipendenti, con dettagli aggiornati e storico operativo",
  "area-merceologica": "Classificazione e gestione delle categorie merceologiche",
  "arrivi-partenze": "Gestione operativa dei movimenti in struttura",
  "assegna-obiettivo": "Definisci obiettivi chiari e incentiva il team al loro raggiungimento",
  "assegnazione-book": "Visualizzazione dell'assegnazione delle camere proposte dall'AI di Sibylla e possibilità di modifica",
  "assegnazioni-incarichi": "Creazione rapida e gestione di task operative con assegnazione automatica o manuale delle attività al personale disponibile",
  "benchmark-fin": "Analisi comparativa dei dati finanziari per identificare punti di forza e aree di miglioramento",
  "break-even": "Valuta il punto di pareggio tra costi e ricavi per decisioni strategiche",
  "budget-analysis": "Visualizza, monitora e analizza i budget per decisioni strategiche",
  "budget-complessivo": "Pianificazione strategica suddivisa per le diverse voci dei ricavi e dei costi",
  "budget-costi": "Controllo di gestione su piano mensile per monitorare le spese, confrontare i dati storici, analizzare le previsioni e verificare l’andamento dell’anno corrente",
  "budget-ricavi": "Dashboard interattiva del revenue con confronto dei dati storici e previsioni future",
  "cabina-controllo": "Panoramica di gestione sulle diverse voci di ricavi e costi",
  "cal-annuale": "Gestisci il tuo catalogo e assegna markup per garantire stabilità e visione a lungo termine",
  "calendario-master": "Visione d'insieme delle strategie applicate alle tariffe, alla distribuzione delle camere e alle prenotazioni di gruppo",
  "calendario-strategie": "Dalla visione all'azione: il tuo piano strategico si applica al mercato in tempo reale. Meno tempo e più risultati",
  "cashflow": "Controlla entrate e uscite di cassa",
  "cassa": "Controllo e gestione centralizzata della cassa e dei movimenti",
  "centro-costo": "Definisci i centri di costo e organizza le spese aziendali",
  "componi-annunci": "Componi annunci di vendita e configura contratti per generare opportunità di business",
  "configura-notifiche": "Monitoraggio e controllo notifiche di sistema e comunicazioni",
  "conti-aperti": "Visualizza e analizza i conti  con stato amministrativo aperto",
  "conti-chiusi": "Visualizza e analizza i conti archiviati con stato amministrativo chiuso",
  "cost-analysis": "Panoramica e report dei costi per ottimizzazione aziendale",
  "crea-acquisto": "Avvia e gestisci acquisti condivisi per ottimizzare costi e volumi",
  "crea-anagrafica": "Crea l’anagrafica di una nuova risorsa e aggiorna subito ruoli e dati contrattuali",
  "crea-magazzino": "Imposta nuovi magazzini e collega flussi di stock e approvvigionamento",
  "crea-outlet": "Inserisci un nuovo outlet, definendo informazioni, categorie e parametri operativi",
  "crea-pratica": "Crea e gestisci le tue pratiche in modo semplice e centralizzato",
  "crea-preventivo": "Crea preventivi personalizzati selezionando prodotti, servizi e dettagli aziendali in modo rapido e automatizzato",
  "crea-prodotto": "Inserisci un nuovo prodotto definendo caratteristiche, categorie e parametri",
  "crea-servizio": "Crea e configura i servizi disponibili per i tuoi clienti",
  "crea-strategia": "Crea strategie guidate in modo smart, ottimizzando ricavi e disponibilità in base alla finestra di prenotazione",
  "crea-struttura": "Inserisci i dati aziendali per registrare una nuova azienda",
  "decision-tree": "Supporto decisionale basato su scenari e dati finanziari per strategie aziendali ottimali",
  "efficienza-operativa": "Ottimizza la disponibilità delle camere con suggerimenti intelligenti per massimizzare occupazione e ricavi",
  "executive-overview": "Dashboard integrata di sintesi per le performace d'impresa",
  "fatturazione-passiva": "Gestisci e monitora tutte le fatture in entrata",
  "finance-overview": "Panoramica completa delle finanze aziendali per monitorare performance e flussi di cassa",
  "gest-advertising": "Programmazione e controllo dei contenuti promozionali e pubblicitari",
  "gest-chiamate": "Visualizza e gestisci il flusso delle chiamate da un’unica interfaccia",
  "gest-comanda": "Gestisci, monitora e aggiorna tutte le comande in tempo reale",
  "gest-documenti": "Gestisci e organizza tutti i documenti in un unico spazio",
  "gestione-preventivi": "Gestisci i preventivi in modo semplice e centralizzato",
  "giornale-impresa": "Controlla l’andamento economico e operativo della tua struttura con una visione completa e strategica",
  "grand-total": "Analisi comparativa con unavisione d'insieme",
  "griglia-disp": "Stato delle prenotazioni per categoria, struttura, tipo di camera e periodo",
  "guest-room": "Monitoraggio e analisi degli ospiti e dell’occupazione delle camere",
  "hr-overview": "Panoramica completa del personale, delle performance e dei trend HR",
  "i-miei-business": "Panoramica completa del tuo business in unico ambiente",
  "i-miei-preventivi": "Visualizza e gesitisci i tuoi preventivi di vendita",
  "i-miei-ristoranti": "Dashboard integrata di sintesi per le performace d'impresa",
  "i-miei-servizi": "Visualizza e gestisci i tuoi servizi disponibili",
  "i-miei-totem": "Gestione contenuti e funzionalità del totem per l’esperienza ospite",
  "imposta-dist": "Analizza le strutture del network e individua opportunità per mercato e tipologia",
  "incoming-analysis": "Analisi dei flussi in entrata per monitorare incassi e previsioni di cassa",
  "inserisci-contratto-v": "Crea un nuovo contratto di vendita con il tuo partner commerciale",
  "interfacce": "Gestione dello stato delle  integrazioni con sistemi esterni",
  "inventario-camere": "Gestione completa delle tipologie e configurazione delle camere",
  "le-mie-destinazioni": "Le destinazioni del tuo catalogo: passeggeri, venduto e marginalità per data e segmento",
  "ledger-analysis": "Controllo e revisione dei registri contabili per garantire correttezza e trasparenza",
  "libro-prenotazioni": "Monitora e gestisci le prenotazioni del tuo ristorante con calendario integrato",
  "lista-fornitori": "Elenco e gestione dei fornitori partner",
  "lista-prodotti": "Panoramica completa dei prodotti disponibili e delle loro caratteristiche",
  "live-display": "La tua area operativa per gestire e ottimizzare il business",
  "log-sistema": "Monitoraggio attività, operazioni utenti e storico eventi di sistema",
  "maggiorazioni": "Aumenta la tua marginalità applicando maggiorazioni e promozioni verso ciascun operatore",
  "maintenance-analysis": "Analisi delle attività di manutenzione per ottimizzare tempi e costi",
  "market-lens": "Analisi comparativa dei prezzi di mercato in tempo reale",
  "miei-contratti-a": "Gestisci e consulta tutti i contratti di acquisto in un unico spazio",
  "miei-contratti-v": "Panoramica completa dei tuoi contratti con dettagli e stato aggiornato",
  "modifica-profilo": "Gestisci e personalizza le informazioni del tuo profilo",
  "modifica-strategia": "Modifica la strategia inserita nella matrice per l'ottimizzazione d'impresa",
  "monitoraggio-canali": "Sintesi dei movimenti per tariffe e disponibilità verso i canali di vendita",
  "monitoraggio-cassa": "Gestione e controllo del flusso di cassa in tempo reale per analizzare le transazioni, controllare il saldo della cassa e prevenire anomalie",
  "monitoraggio-perf": "Controllo e analisi dei risultati e delle performance del personale",
  "monitoraggio-pratiche": "Visualizza e monitora lo stato di avanzamento delle pratiche",
  "monthly-trend": "Analisi comparativa su base mensile",
  "movimenti-attesa": "Tieni sotto controllo i conti pronti per essere fatturati",
  "movimenti-scorte": "Analisi e monitoraggio dei movimenti di magazzino",
  "movimenti-soggiorno": "Visualizza e gestisci tutti i movimenti del soggiorno dei tuoi ospiti",
  "occ-analysis": "Analisi del tasso di occupazione e della capacità disponibile per ogni tipologia di camera",
  "on-the-book": "Analisi dettagliata delle prenotazioni per ottimizzare occupazione e ricavi",
  "op-overview": "Panoramica delle operazioni giornaliere e dei KPI di gestione",
  "open-board": "Accedi in tempo reale alla disponibilità delle strutture e gestisci l'intero processo di prenotazione da un unico ambiente operativo",
  "ordine-servizio": "Generazione rapida di ordini di servizio per housekeeping, manutenzione, reception e altri reparti",
  "organigramma": "La mappa completa dei ruoli e team della tua organizzazione",
  "ospiti-giorno": "Scopri l’elenco giornaliero degli ospiti",
  "ospiti-in-casa": "Monitoraggio degli ospiti attualmente in struttura",
  "panoramica-acquisti": "Analisi completa degli acquisti effettuati, con report, trend e indicatori di performance",
  "piani-tar": "Gestisci piani tariffari in smart per offrire prezzi dinamici su ogni segmento di mercato evitando disparity rate",
  "pick-up": "Analisi dinamica dell'andamento delle prenotazioni nel tempo",
  "planner": "Gestione operativa in tempo reale delle prenotazioni e della disponibilità delle camere",
  "portafoglio-aziendale": "Monitoraggio centralizzato per operazioni vantaggiose, sicure, rapide e connesse al mercato in tempo reale",
  "portafoglio-personale": "Dai valore al tuo lavoro: guadagna e utilizza il credito del tuo portafoglio",
  "preliminare": "Controlla e verifica i dati prima della chiusura definitiva, garantendo correttezza e completezza",
  "prenotazioni-ids": "Visione centralizzata per monitoraggio in tempo reale delle prenotazioni ricevute dai canali di distribuzione online",
  "pricing-benchmark": "in pending (momentaneamente)",
  "profile-analysis": "Analizza i profili dei dipendenti per monitorare ruoli, performance e competenze",
  "profit-trend": "Analizza trend di profitti e marginalità aziendale",
  "registro-chiusure": "Visualizza e gestisci lo storico delle chiusure effettuate, con dettagli e riepiloghi",
  "registro-presenze": "Gestione delle presenze del personale in tempo reale. Con tracciamento di ingressi, uscite, assenze, permessi e ferie",
  "reset-profili": "Configura e gestisci i profili in modo centralizzato",
  "richieste-operative": "Invia, aggiorna e controlla le richieste operative verso la struttura in modo semplice ed efficace",
  "rilevamento-presenze": "Report dei dati aggregati per nazionalità e delle presenze registrate",
  "ruoli-funzioni": "Gestisci in modo smart ruoli e profili per un’organizzazione efficiente",
  "sala-ristorante": "Gestisci layout sala, assegnazione tavoli in tempo reale",
  "sale-tavoli": "Disposizione della sala e servizio ai tavoli",
  "sales-overview": "Analisi performance commerciale, ricavi e marginalità",
  "scadenzario": "Monitora e organizza la tua giornata, eventi e scadenze",
  "schedine": "Archivio automatico e centralizzato delle presenze",
  "screening-open": "Aumenta l'accuratezza dei suggerimenti attraverso uno screening dedicato per ogni tipologia di camera assegnata a ciascun canale di vendita",
  "segment-analysis": "Analisi delle performance per cluster e segmenti di mercato",
  "segnalazioni": "Gestione delle richieste di intervento tecnico/operativo all’interno della struttura con tracking in tempo reale",
  "servizi-di-rete": "Accedi e gestisci i servizi condivisi nella tua rete",
  "simulatore": "Prova oggi la decisione di domani, senza alcun rischio",
  "stato-camere": "Controlli arrivi, partenze e cambi camera programmati",
  "sugg-data-driven": "Indicazioni strategiche data driven su tariffe numero di camere da mettere a disposizione e richieste extra per gruppi",
  "tableau-book": "Inserimento e monitoraggio delle prenotazioni individuali e di gruppo",
  "tariffe-disp": "Gestisci tariffe e disponibilità sui diversi canali di vendita per struttura, giorno e intervallo temporale",
  "turni-personale": "Pianificazione e visualizzazione dei turni di lavoro",
  "value-analysis": "Analisi del markup e delle performance di occupancy e ADR",
  "wif-analysis": "Simula scenari e valuta l’impatto delle decisioni sul business",
}

/** Sottotitolo per una pagina (gestisce gli id con parametro "id:param"). */
export const subtitleForPage = (page: string): string | undefined =>
  PAGE_SUBTITLES[page.includes(':') ? page.slice(0, page.indexOf(':')) : page]
